# Generated by Django 6.1.1 on 2026-09-13 23:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('listing_count', models.PositiveIntegerField(default=0)),
                ('stars_count', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'User statistic',
                'verbose_name_plural': 'User statistics',
                'db_table': 'user_statistics',
            },
        ),
        migrations.CreateModel(
            name='ListingStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Listing statistic',
                'verbose_name_plural': 'Listing statistics',
                'db_table': 'listing_statistics',
            },
        ),
    ]
