# Generated by Django 6.1.1 on 2026-09-13 23:24

import django.core.validators
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalListing',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID id')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('apartment_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(30)], verbose_name='apartment name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('address', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='address')),
                ('floor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(165)], verbose_name='floor')),
                ('country', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='country')),
                ('room_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='number of rooms')),
                ('shower_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='number of shower rooms')),
                ('toilets_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='number of toilets')),
                ('input_type', models.CharField(choices=[('key', 'Key'), ('pin_kode', 'Pin_kode'), ('card', 'Card')], default='key', max_length=10, verbose_name='how to get in')),
                ('parking', models.BooleanField(default=False, verbose_name='availability of parking')),
                ('can_smoke', models.BooleanField(default=False, verbose_name='Is smoking allowed?')),
                ('wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('indoor_fireplace', models.BooleanField(default=False, verbose_name='Is there a fireplace')),
                ('can_pets', models.BooleanField(default=False, verbose_name='Are pets allowed?')),
                ('facilities_for_guests_with_disabilities', models.BooleanField(default=False, verbose_name='Accessibility for people with disabilities?')),
                ('air_conditioner', models.BooleanField(default=False, verbose_name='Is there air conditioning?')),
                ('elevator', models.BooleanField(default=False, verbose_name='Is there an elevator?')),
                ('photo', models.TextField(blank=True, max_length=100, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='price per night')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Listing',
                'verbose_name_plural': 'historical Listings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('apartment_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(30)], verbose_name='apartment name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('address', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='address')),
                ('floor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(165)], verbose_name='floor')),
                ('country', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='country')),
                ('room_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='number of rooms')),
                ('shower_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='number of shower rooms')),
                ('toilets_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='number of toilets')),
                ('input_type', models.CharField(choices=[('key', 'Key'), ('pin_kode', 'Pin_kode'), ('card', 'Card')], default='key', max_length=10, verbose_name='how to get in')),
                ('parking', models.BooleanField(default=False, verbose_name='availability of parking')),
                ('can_smoke', models.BooleanField(default=False, verbose_name='Is smoking allowed?')),
                ('wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('indoor_fireplace', models.BooleanField(default=False, verbose_name='Is there a fireplace')),
                ('can_pets', models.BooleanField(default=False, verbose_name='Are pets allowed?')),
                ('facilities_for_guests_with_disabilities', models.BooleanField(default=False, verbose_name='Accessibility for people with disabilities?')),
                ('air_conditioner', models.BooleanField(default=False, verbose_name='Is there air conditioning?')),
                ('elevator', models.BooleanField(default=False, verbose_name='Is there an elevator?')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='listing_photo/')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='price per night')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'db_table': 'listings',
                'ordering': ['apartment_name', 'country', 'room_count'],
            },
        ),
    ]
