# Generated by Django 6.1.1 on 2026-09-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallisting',
            name='photo',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(default=1, upload_to='listing_photo/'),
            preserve_default=False,
        ),
    ]
