# Generated by Django 6.1.1 on 2026-09-14 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_listings_country_a47cb9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallisting',
            name='max_guests',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='maximum number of guests'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='max_guests',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='maximum number of guests'),
            preserve_default=False,
        ),
    ]
