# Generated by Django 6.1.1 on 2026-09-16 17:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_historicallisting_max_guests_listing_max_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallisting',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo',
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='apartment_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='apartment name'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='apartment_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='apartment name'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='listing_photos/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'db_table': 'photos',
                'ordering': ['created_at'],
            },
        ),
    ]
