# Generated by Django 6.1.1 on 2026-09-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_historicallisting_photo_remove_listing_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallisting',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('room', 'Room')], default='apartment', max_length=15, verbose_name='property type'),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('room', 'Room')], default='apartment', max_length=15, verbose_name='property type'),
        ),
    ]
