# Generated by Django 6.1.1 on 2026-09-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_historicallisting_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallisting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
