# Generated by Django 6.1.1 on 2026-09-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_historicallisting_is_active_listing_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallisting',
            name='country',
            field=models.CharField(choices=[('DE', 'Germany')], default='DE', max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(choices=[('DE', 'Germany')], default='DE', max_length=2, verbose_name='country'),
        ),
    ]
