# Generated by Django 6.1.1 on 2026-09-22 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_historicallisting_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallisting',
            name='floors_count',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='number of floors'),
        ),
        migrations.AddField(
            model_name='listing',
            name='floors_count',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='number of floors'),
        ),
        migrations.AlterField(
            model_name='historicallisting',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(165)], verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(165)], verbose_name='floor'),
        ),
    ]
