# Generated by Django 6.1.1 on 2026-09-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_historicallisting_floors_count_listing_floors_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallisting',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio')], default='apartment', max_length=15, verbose_name='property type'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio')], default='apartment', max_length=15, verbose_name='property type'),
        ),
    ]
