# Generated by Django 6.1.1 on 2026-09-13 23:24

import django.core.validators
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='price')),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('bank_cart', 'Bank_cart'), ('kripto', 'Kripto')], default='bank_cart', max_length=10, verbose_name='payment type')),
                ('prepayment_type', models.CharField(choices=[('free_booking', 'Free_booking'), ('partial_prepayment', 'Partial_prepayment'), ('full_payment', 'Full_payment')], default='partial_prepayment', max_length=20, verbose_name='prepayment type')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBooking',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID id')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='price')),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('bank_cart', 'Bank_cart'), ('kripto', 'Kripto')], default='bank_cart', max_length=10, verbose_name='payment type')),
                ('prepayment_type', models.CharField(choices=[('free_booking', 'Free_booking'), ('partial_prepayment', 'Partial_prepayment'), ('full_payment', 'Full_payment')], default='partial_prepayment', max_length=20, verbose_name='prepayment type')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Booking',
                'verbose_name_plural': 'historical Bookings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
