# Generated by Django 6.1.1 on 2026-09-14 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of guests'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='guests_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of guests'),
            preserve_default=False,
        ),
    ]
