# Generated by Django 6.1.1 on 2026-09-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_card_last4_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='prepayment_type',
        ),
        migrations.RemoveField(
            model_name='historicalbooking',
            name='prepayment_type',
        ),
    ]
